converter/urls.py
from django.conf.urls import patterns, url
from converter import views

urlpatterns = patterns("", 
    url(r'^$', views.index, name='index'),
    url(r'^results/$', views.results, name='results'),
)

num2words/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'num2words.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^converter/', include('converter.urls', namespace='converter'))
)

converter/models.py
import os
import sys
PATH_TO_RULES = '/'.join(str(os.path.abspath(__file__)).split('/')[:-1])+'/lib'
sys.path.insert(0,PATH_TO_RULES)
from conv import NumToWord
import localization


class Engine(object):
	info = 'Please input number like 23448592.23'
	langs_available = [lang for lang in localization.languages]
	currencies_available = localization.available_currenceis

	def __init__(self, language=None, currency=None, number=None):
		if language:
			convertor = NumToWord(language, currency)
			self.result = convertor.convert(number)
		else:
			self.result = language
		self.number = number

# Create your models here.

x = NumToWord('ua', 'uah')

print x._lang_family

converter/views.py
from django.shortcuts import render
from models import Engine

def index(request):
	return render(request, 'converter/index.html', {'engine': Engine()})

def results(request):
	language = request.POST['language']
	currency = request.POST['currency']
	number = request.POST['number'].strip()

	return render(request, 'converter/index.html', {'engine': Engine(language, currency, number)})

print Engine.info
# Create your views here.

converter/templates/converter/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'converter/style.css' %}" />
<script type="text/javascript">
    var DICT = {
        {% for k, v in engine.currencies_available.items %}
            "{{k}}": [
                {% for x in v %}
                    "{{x}}" {% if not forloop.last %}, {% endif %}
                {% endfor %}
            ]
            {% if not forloop.last %}, {% endif %}
         {% endfor %}
    };
    
    function pickCurrencies() {
        var lang = document.getElementById("languages").value;
        // rewrite currencies select if languages selected an empty field
        if ( lang == "" ) { 
            document.getElementById("currencies").innerHTML = "<option></option>";
            return;
        }
        //
        var list = DICT[lang]
        var result = "<option value=\"\" ></option>\n";
        var len = list.length;

        for (var i = 0; i < len; i++) {
            result += "<option value=\"" + list[i] + "\" >" + list[i] + "</option>\n"
        };
        document.getElementById("currencies").innerHTML = result;
    }
    function validateInput() {
        var val = $('#converterNumber').val()
        var reg = /^[0-9]+(\.[0-9]{1,2})?$/g;
        var selectedCurrency = $('#currencies').find(':selected').text();

        if ( reg.test(val) && selectedCurrency ) {
            $('#submitConvert').prop('disabled', false);
        } else {
            $('#submitConvert').prop('disabled', true);
        }
    }

    $(document).ready( function () {
        $('#converterNumber').keyup( validateInput );
    });    
</script>

{% if engine.result %}
    <div class="result"> Result is: {{engine.result}} </div>
{% endif %}

<form name="converter" action="{% url 'converter:results' %}" method="post">
    {% csrf_token %}
    <label for="language">language</label>
    <!-- call validateInput() with perpes to desable convert button if languages selected an empty field -->
    <select id="languages" name="language" onchange="pickCurrencies(); validateInput();">
        <option value="" ></option>
        {% for lang in engine.langs_available %}
        <option value="{{lang}}">{{lang}}</option>
        {% endfor %}
    </select><br>
    <label for="currency">currency  </label>
    <select id="currencies" name="currency" onchange="validateInput()" ></select>
    <br>
    <label for="number">{{engine.info}}</label>
    <br>
    <input type="text" id="converterNumber" name="number" 
        {% if engine.number %} value="{{engine.number}}" {% endif %}>
    <br>
    <input type="submit" disabled id="submitConvert" value="Convert">
</form>